#pragma once
#include <map>
#include <string>
#include <vector>
namespace NewRT
{
namespace TKP
{

struct KeyEvent
{
    uint16_t code;
    bool pressed;
};

enum TkpKeyCode
{
    KEY_CODE_RESERVED = 0,
    KEY_PSDM_MOTION   = 120,
    KEY_GANTY_MOTION  = 121,
    KEY_XRAY_ON       = 122,
    KEY_MOTION_ENABLE = 123,
    XRAY_STATUS_INPUT = 124,
    PVS_MODE_INPUT    = 125,
    KEY_SNOUT_MOTION,
    KEY_BEAM_ON,
    KEY_BEAM_XRAY_PAUSE,
    KEY_BEAM_XRAY_STOP,
    KEY_NEXT_POS,
    KEY_CODE_MAX
};

enum TkpKeyEvent
{
    EVT_RESERVED = 0,
    EVT_F7_PRESSED,
    EVT_F7_RELEASED,
    EVT_GANTY_MOTION_PRESSED,
    EVT_GANTY_MOTION_RELEASED,
    EVT_SNOUT_MOTION_RRESSED,
    EVT_SNOUT_MOTION_RELEASED,
    EVT_PSDM_MOTION_PRESSED,
    EVT_PSDM_MOTION_RELEASED,
    EVT_MOTION_ENABLE_PRESSED,
    EVT_MOTION_ENABLE_RELEASED,
    EVT_BEAM_ON_PRESSED,
    EVT_BEAM_ON_RELEASED,
    EVT_BEAM_XRAY_PAUSE_RRESSED,
    EVT_BEAM_XRAY_PAUSE_RELEASED,
    EVT_BEAM_XRAY_STOP_PRESSED,
    EVT_BEAM_XRAY_STOP_RELEASED,
    EVT_NEXT_POS_PRESSED,
    EVT_NEXT_POS_RELEASED,
    EVT_XRAY_ON_PRESSED,
    EVT_XRAY_ON_RELEASED,
    EVT_XRAY_STATUS_INPUT_INACTIVE,
    EVT_XRAY_STATUS_INPUT_ACTIVE,
    EVT_PVS_MODE_INPUT_CBCT,
    EVT_PVS_MODE_INPUT_OTH,
    EVT_MAX
};

enum BACKLIGHT_STATE
{
    BACKLIGHT_OFF = 0,
    BACKLIGHT_ON,
    BACKLIGHT_BLINK_SLOW,
    BACKLIGHT_BLINK_FAST
};

enum XRAY_OUTPUT
{
    XRAY_DISABLE,
    XRAY_ENABLE
};
} // namespace TKP
} // namespace NewRT
